"""update nquin_2

Revision ID: 06051a6a28f8
Revises: 586358411415
Create Date: 2026-01-07 10:57:07.934166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06051a6a28f8'
down_revision = '586358411415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('logs')
    with op.batch_alter_table('tour_guide_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guide_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['guide_id'], ['id'])
        batch_op.drop_column('guide_name')

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('tour_guide_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guide_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('guide_id')

    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_pkey'))
    )
    op.drop_table('user_logs')
    # ### end Alembic commands ###
