"""1

Revision ID: 4e981624a82b
Revises: 63919a9ad9a9
Create Date: 2026-01-14 14:57:07.726205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e981624a82b'
down_revision = '63919a9ad9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
