"""capnhat

Revision ID: 5edc462dc13a
Revises: c75e9a23e1b5
Create Date: 2026-01-26 21:20:46.710865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edc462dc13a'
down_revision = 'c75e9a23e1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_guide_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_guide_assignments', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
