"""1

Revision ID: 63919a9ad9a9
Revises: 6d0a8fbd175d
Create Date: 2026-01-14 14:53:48.873423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63919a9ad9a9'
down_revision = '6d0a8fbd175d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('itinerary')

    # ### end Alembic commands ###
