"""Cap nhat

Revision ID: 8f30ef933a54
Revises: 4e981624a82b
Create Date: 2026-01-26 19:20:24.114828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f30ef933a54'
down_revision = '4e981624a82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tour_guides_status'))
        batch_op.drop_index(batch_op.f('idx_tour_guides_supplier'))

    op.drop_table('tour_guides')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_checked_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    with op.batch_alter_table('tour_guide_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_assignments_guide'))
        batch_op.drop_index(batch_op.f('idx_assignments_tour'))

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_column('max_people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_people', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('tour_guide_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_assignments_tour'), ['tour_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_assignments_guide'), ['guide_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('is_checked_in')

    op.create_table('tour_guides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('license_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('years_of_experience', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('languages', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('specialties', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('available', 'busy', 'on_leave', name='guide_status'), server_default=sa.text("'available'::guide_status"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], name=op.f('tour_guides_supplier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tour_guides_pkey'))
    )
    with op.batch_alter_table('tour_guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tour_guides_supplier'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tour_guides_status'), ['status'], unique=False)

    # ### end Alembic commands ###
